### PR TITLE
Fix #12, update to Elm 0.18

### LINKED ISSUE #12: doesn't work on elm 0.18
the version requirements of the template is < 0.18

### PR DESCRIPTION
**Pull request by shamansir**
Fixes #12

### CODE REVIEW

**Comment by shamansir** [comment]
Seems not to work with:

```
Html.program
  { init = init
  , view = view
  , update = update
  , subscriptions = subscriptions
  }
```

I'll test why, fix it, and re-open this PR

**Comment by mukeshsoni** [comment]
@shamansir  that's awesome 🤘🏼

**Comment by shamansir** [comment]
It turned out it was the problem with my code, not elm-instant's fault.

**Comment by shamansir** [comment]
@mukeshsoni please merge with caution, could have issues I failed to notice.

**Comment by mukeshsoni** [comment]
@shamansir In that case will take a look in the morning :)

**Comment by oli-obk** [comment]
Any update on this?

**Comment by mukeshsoni** [comment]
@oli-obk I am not able to find the time to merge and verify this. Can give full write access to both the repo as well as the atom plugin if anyone wants to go ahead with it.

**Comment by oli-obk** [comment]
@shamansir I won't be able to do this on my own, but if you're also willing to pitch in, we could shepherd elm-instant together.

**Comment by shamansir** [comment]
@oli-obk Actually the only problem I had in my case is that HtmlProgram wasn't rendering two times if was repeated and I wasn't sure how to fix that. 

My own fork is for what we've planned with @mukeshsoni for future / some ideas for improvement and it's in a stale state. 

I've planned to use type information I may get from `node-elm-repl` and display components like these ones https://github.com/shamansir/elm-playground-components instead of just embedding the program, so it could look more like Swift Playgrounds, with plots for functions/loops etc.

If you want to participate, feel free to connect, the optimal place is [elm-lang](http://elmlang.herokuapp.com/) slack, I suppose, just DM me there.

**Comment by mukeshsoni** [comment]
@shamansir @oli-obk 
I tried the changed code. Breaks on changing files. Works for the first open file only. Will take a look and see if i can fix it.

**Pull request merged**
